apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-devops-api.fullname" . }}
  labels:
    {{- include "flask-devops-api.labels" . | nindent 4 }}
    monitoring: prometheus
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: flask-devops-api
